export const HttpResponse = {
    SERVER_ERROR: "Internal server error",
    USER_EXIST: "User already exist",
    PAGE_NOT_FOUND: "Route not found",
    USER_NOT_FOUND: "User not found",
    PASSWORD_INCORRECT: "Incorrect password, try again",
    PASSWORD_REQUIRED: "Password is required",
    PASSWORD_NOT_MATCH: "Passwords do not match",
    EMAIL_AND_PASSWORD_REQUIRED: "Email and password are required",
    MISSING_REQUIRED_FIELDS: 'Missing required fields',
    NO_TOKEN: "Token not provided",
    OTP_VERIFIED_SUCCESS: "OTP verified",
    OTP_RESENT_SUCCESS: "OTP resent successfully",
    OTP_INCORRECT: "Incorrect OTP, try again",
    OTP_NOT_FOUND: "OTP not found",
    OTP_EXPIRED: "OTP expired",
    OTP_VERIFICATION_REQUIRED: "OTP verification is required",
    INVALID_CREDENTIALS: "Invalid credentials",
    USER_CREATION_FAILED: "User creation failed",
    USER_CREATION_SUCCESS: "User created successfully",
    GOOGLE_LOGIN_SUCCESS: "Logged in with Google successfully",
    EMAIL_EXIST: "Email already exist",
    INVALID_EMAIL: "Invalid email address",
    EMAIL_REQUIRED: "Email is required",
    PHONE_REQUIRED: "Phone is required",
    UNEXPECTED_KEY_FOUND: "Unexpected key found",
    RESET_PASS_LINK: "Link for resetting password is sended to email",
    TOKEN_EXPIRED: "Token not valid or expired!",
    PASSWORD_CHANGE_SUCCESS: "Password changed successfully!",
    PASSWORD_RESET_EXPIRED: "Password reset is expired",
    UNAUTHORIZED: "Unauthorized access!",
    USERNAME_EXIST: "Username Already Exist",
    NO_PAYLOAD: "Payload not found",
    USERNAME_CHANGED: "Username has been changed successfully",
    SAME_USERNAME: "Cannot change to old username",
    RESOURCE_FOUND: "Resource found.",
    RESOURCE_UPDATED: "Resource updated.",
    PROFILE_PICTURE_CHANGED: "Profile picture changed successfully",
    LOGOUT_SUCCESS: "User Logout successfully",
    PLAN_NOT_FOUND: "Plan not found",
    NO_PLANS: "No plans available",
    INVALID_ID: "Invalid ID format",
    SKILL_NOT_FOUND: "Skill not found",
    SKILL_ID_REQUIRED: "Skill ID is required",
    REQUIRED_TITLE: "Blog title is required",
    REQUIRED_CONTENT: "Blog content is required",
    BLOG_IMAGE_NOT_FOUND: "Blog thumbnail not found",
    USER_ALREADY_ACTIVE: "User already has an active subscription",
    PAYMENT_VERIFICATION_FAILED: "Payment verification failed",
    SUBSCRIPTION_NOT_FOUND: "Subscription not found",
    NO_ACTIVE_SUBSCRIPTION: "No active subscription found",
    ROLE_NOT_FOUND: "Role not found",
    NO_FILE_FOUND: "No file uploaded",
    ACCESS_DENIED: "Access denied",
    INVALID_STATUS: "Invalid status",
    REFRESH_TOKEN_MISSING: "Refresh token missing",
    PROPOSAL_NOT_FOUND: "Proposal not found",
    JOB_NOT_FOUND: "Job not found",
};