name: Backend CD

on: 
  push: 
    branches: ["main"]
    paths: 
      - "backend/**"

jobs: 
  deploy: 
    runs-on: ubuntu-latest

    defaults: 
      run: 
        working-directory: ./backend

    steps: 
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: | 
          docker build -t ${{ secrets.DOCKER_USERNAME }}/fad-dev:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/fad-dev:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with: 
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/fad-dev:latest

            # Stop and remove the existing container
            docker stop clientfree_backend || true
            docker rm clientfree_backend || true

            # Run the new container
            docker run -d \
              --name clientfree_backend \
              --env-file /home/ubuntu/.env \
              -p 3000:3000 \
              --restart unless-stopped \
              ${{ secrets.DOCKER_USERNAME }}/fad-dev:latest
